# -*- coding: utf-8 -*-
"""1_sales_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJ0P4ZHGMPiovOCFC2HrzBtfEGmXQgrn
"""

"""Project 1: Sales & E-Commerce Analytics (dataset: Superstore Sales CSV from Kaggle)"""
import os
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

os.makedirs("outputs", exist_ok=True)
DB_URL = os.getenv("DB_URL", "sqlite:///portfolio.db")  # e.g. mysql+pymysql://user:pwd@localhost/portfolio

# 1. Load and clean
df = pd.read_csv("data/Sample - Superstore.csv", encoding="latin-1")
df.columns = [c.strip().lower().replace(" ", "_").replace("-", "_") for c in df.columns]
print("Rows before cleaning:", len(df))
df = df.drop_duplicates().dropna(subset=["order_id", "customer_id", "sales"])
df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)
df["order_year"] = df["order_date"].dt.year
df["sales"] = pd.to_numeric(df["sales"], errors="coerce")
df["profit"] = pd.to_numeric(df["profit"], errors="coerce")

print("Rows after cleaning:", len(df))

# 2. KPIs
revenue, profit = df["sales"].sum(), df["profit"].sum()
orders = df["order_id"].nunique()
orders_per_cust = df.groupby("customer_id")["order_id"].nunique()
print(f"Revenue {revenue:,.0f} | Profit {profit:,.0f} | AOV {revenue/orders:,.2f}")
print(f"Repeat customers: {(orders_per_cust > 1).mean():.1%}")
region = df.groupby("region")["sales"].sum().sort_values(ascending=False)
print((region / revenue * 100).round(1))

# 3. Charts (use these as GitHub screenshots)
region.plot(kind="bar", color="#2E75B6", title="Revenue by Region")
plt.ylabel("Revenue"); plt.tight_layout(); plt.savefig("outputs/revenue_by_region.png", dpi=150); plt.clf()
df.groupby("order_year")["sales"].sum().plot(marker="o", title="Yearly Revenue Trend")
plt.tight_layout(); plt.savefig("outputs/yearly_revenue.png", dpi=150); plt.clf()
df.groupby("category")["profit"].sum().plot(kind="bar", color="#548235", title="Profit by Category")
plt.tight_layout(); plt.savefig("outputs/profit_by_category.png", dpi=150); plt.clf()

# 4. Save cleaned data + load into database for the SQL file
df.to_csv("data/clean_sales.csv", index=False)
df.to_sql("sales", create_engine(DB_URL), if_exists="replace", index=False)
print("Done. Charts in outputs/, table 'sales' loaded.")