# -*- coding: utf-8 -*-
"""1_sales_queries.sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYiautV_Ji1AOexc5rF_XzL2Yxmr0yhm
"""

-- Project 1: Sales & E-Commerce (table: sales). Works in MySQL and SQLite.

-- 1. Revenue, profit, profit margin
SELECT ROUND(SUM(sales),2) AS revenue, ROUND(SUM(profit),2) AS profit,
       ROUND(SUM(profit)*100.0/SUM(sales),2) AS profit_margin_pct
FROM sales;

-- 2. Average order value
SELECT ROUND(SUM(sales)/COUNT(DISTINCT order_id),2) AS avg_order_value FROM sales;

-- 3. Revenue share by region (finds the top region)
SELECT region, ROUND(SUM(sales),2) AS revenue,
       ROUND(SUM(sales)*100.0/(SELECT SUM(sales) FROM sales),1) AS revenue_share_pct
FROM sales GROUP BY region ORDER BY revenue DESC;

-- 4. Yearly sales growth
SELECT order_year, ROUND(SUM(sales),2) AS revenue,
       ROUND((SUM(sales) - LAG(SUM(sales)) OVER (ORDER BY order_year))*100.0
             / LAG(SUM(sales)) OVER (ORDER BY order_year),1) AS growth_pct
FROM sales GROUP BY order_year ORDER BY order_year;

-- 5. Repeat purchase rate
SELECT ROUND(SUM(CASE WHEN n > 1 THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS repeat_customer_pct
FROM (SELECT customer_id, COUNT(DISTINCT order_id) AS n FROM sales GROUP BY customer_id) t;

-- 6. Top 10 products by profit
SELECT product_name, ROUND(SUM(profit),2) AS profit FROM sales
GROUP BY product_name ORDER BY profit DESC LIMIT 10;

-- 7. Loss-making sub-categories (subquery)
SELECT sub_category, ROUND(total_profit,2) AS total_profit
FROM (SELECT sub_category, SUM(profit) AS total_profit FROM sales GROUP BY sub_category) x
WHERE total_profit < 0;